{% set name = "markdownify" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/markdownify-{{ version }}.tar.gz
  sha256: d373eeac3ab6fa28bb1cdcb6432663e5aee85eae3cc4909f70f55a0a9cd1aea4

build:
  entry_points:
    - markdownify = markdownify.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - beautifulsoup4 >=4.9,<5
    - six >=1.15,<2

test:
  imports:
    - markdownify
  commands:
    - pip check
    - markdownify --help
  requires:
    - pip

about:
  home: http://github.com/matthewwithanm/python-markdownify
  summary: Convert HTML to markdown.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gscoppino
