{% set name = "markdownify" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/markdownify-{{ version }}.tar.gz
  sha256: a62a7a216947ed0b8dafb95b99b2ef4a0edd1e18d5653c656f68f03db2bfb2f1

build:
  entry_points:
    - markdownify = markdownify.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - beautifulsoup4 >=4.9,<5
    - six >=1.15,<2

test:
  imports:
    - markdownify
  commands:
    - pip check
    - markdownify --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/matthewwithanm/python-markdownify
  summary: Convert HTML to markdown.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gscoppino
